version: "3.8"
services:
  apache:
    container_name: apache
    build: './apache/'
    ports:
      - "${HOST_MACHINE_PORT}:80"
    volumes:
      - ${DOC_ROOT}:/var/www/html/
  php:
    container_name: php
    build: './php/'
    depends_on:
      - apache
      - mysql
    volumes:
      - ${DOC_ROOT}:/var/www/html/
  mysql:
    container_name: mysql
    build: './mysql/'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql/data:/var/lib/mysql